Manifest-Version=1.0
Implementation-Title=io.micrometer#micrometer-core;1.4.1
Implementation-Version=1.4.1
Built-Status=integration
Built-By=circleci
Built-OS=Linux
Build-Date=2020-03-30_07:31:07
Gradle-Version=6.3
Module-Source=/micrometer-core
Module-Origin=git@github.com:micrometer-metrics/micrometer.git
Change=44554d3
Branch=44554d3d6d6c40f4c8cf525e18e9b63615668d99
Build-Host=9f5d8fa4930e
Build-Job=LOCAL
Build-Number=LOCAL
Build-Id=LOCAL
Created-By=14+36 (Oracle Corporation)
Build-Java-Version=14
Module-Owner=jschneider@pivotal.io
Module-Email=jschneider@pivotal.io
X-Compile-Target-JDK=14
X-Compile-Source-JDK=14